apiVersion: batch/v1
kind: CronJob
metadata:
  name: poem-display
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: poem-display
              image: sandrosrc/poem-display:latest
          restartPolicy: OnFailure